import type { ResearchRecord } from "@/lib/types";

const cites = (ns: number[]) => ns.map((n) => `[${n}]`).join("");

export function toMarkdown(r: ResearchRecord): string {
  const out: string[] = [`# ${r.title}`, "", `> ${r.question}`, ""];
  const res = r.result;
  if (res.mode === "ask") {
    const d = res.data;
    out.push(`**Confidence:** ${d.confidence}`, "", d.answer, "");
    if (d.keyPoints.length) out.push("## Key points", ...d.keyPoints.map((k) => `- ${k}`), "");
    if (d.gaps.length) out.push("## Gaps", ...d.gaps.map((k) => `- ${k}`), "");
    if (d.followUps.length) out.push("## Follow-up questions", ...d.followUps.map((k) => `- ${k}`), "");
  } else if (res.mode === "compare") {
    const d = res.data;
    out.push(d.summary, "", `| Dimension | ${d.subjects.join(" | ")} |`, `|---|${d.subjects.map(() => "---").join("|")}|`);
    for (const row of d.rows)
      out.push(`| ${row.dimension} | ${row.cells.map((c) => `${c.value} ${cites(c.citations)}`.replace(/\|/g, "/")).join(" | ")} |`);
    out.push("", `**Takeaway:** ${d.takeaway}`, "");
  } else {
    const d = res.data;
    out.push(`**Decision:** ${d.decision}`, "", `**Verdict:** ${d.verdict}`, "", `**Recommendation:** ${d.recommendation}`, "");
    if (d.context) out.push("## Context", d.context, "");
    if (d.options.length) {
      out.push("## Options");
      for (const o of d.options) {
        out.push(`### ${o.name}`, o.summary, ...o.pros.map((p) => `- ✅ ${p}`), ...o.cons.map((p) => `- ⚠️ ${p}`), "");
      }
    }
    if (d.evidence.length) out.push("## Evidence", ...d.evidence.map((e) => `- ${e.claim} ${cites(e.citations)}`), "");
    if (d.risks.length) out.push("## Risks", ...d.risks.map((k) => `- **${k.severity}** — ${k.risk} → ${k.mitigation}`), "");
    if (d.nextSteps.length) out.push("## Next steps", ...d.nextSteps.map((s, i) => `${i + 1}. ${s}`), "");
  }
  if (r.notes) out.push("## Analyst notes", r.notes, "");
  out.push("## Sources");
  for (const s of r.sources) out.push(`${s.n}. **${s.docName}** — ${s.location}`, `   > ${s.text.replace(/\n+/g, " ").slice(0, 400)}`);
  out.push("", `_Generated by Cairn · ${new Date(r.createdAt).toLocaleString("en-GB")}_`);
  return out.join("\n");
}
